version: '3.9'
services:
  app:
    build: .
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
